[pytest]
# Tell pytest where your settings are (change 'core' if your main folder is named differently)
DJANGO_SETTINGS_MODULE = core.settings

# Tell pytest what files to look for when hunting for tests
python_files = tests.py test_*.py *_tests.py