# Generated by Django 5.2.13 on 2026-06-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
